# **컨프리헨션 & 람다**

* <b>for문 1~10 짝수만 출력

In [3]:
for v in range(1,11):
    if (v%2 ==0) :
        print(v)

2
4
6
8
10

In [4]:
[v for v in range(1,11) if (v%2 ==0)  ]

[2, 4, 6, 8, 10]

* <b>for문 1~5 3보다크면 값*2, 그렇지 않으면 값 출력

In [5]:
for v in range(1,6):
    if (v>3) :
        print(v*2)
    else :
        print(v)

1
2
3
8
10

In [6]:
[v*2 if (v>3)  else v for v in range(1,6)  ]

[1, 2, 3, 8, 10]

# **람다(lambda)**
* 익명(이름없는) 함수
* 1회용

* 함수이름 : add
* 파라미터 : 숫자2개 
* 합산 결과 리턴

* <b>람다 예제

In [14]:
def ncheck(n) :
    print(n*2)

In [15]:
ncheck2 = lambda n : n*2

In [16]:
ncheck(6)

12

In [17]:
ncheck2(6)

12

* <b>람다 예제

In [7]:
def add(n1, n2) :
    res = n1 + n2
    return res

a= add(1, 2)    
print(a)

3

In [20]:
add2 = lambda n1, n2 : n1 + n2

a= add2(1, 2)    
print(a)

3

* <b>람다 예제

```python
if n > 10 :
    n 
else :
    0

n if n > 10  else 0

In [25]:
a = lambda n : n if n > 10  else 0
a(30)

30

* <b>람다 예제

In [30]:
def add(n1) :
    return n1 + 10

In [31]:
a = lambda n1 : add(n1)
a(5)

15

* <b>람다 예제

In [33]:
def check(n1) :
    res = 0
    if n1 > 10 : 
        res = n1 * 2
    else :
        res = n1 
    return res    

check(2)

2

In [35]:
a = lambda n1 : n1 * 2 if n1 > 10  else n1 
a(2)

2

In [37]:
a = lambda n1 : check(n1)
a(20)

40

# **DataFrame을 활용한 lambda**

In [45]:
import numpy as np
import pandas as pd

In [49]:
df = pd.DataFrame({
    "name": ["kim", "hong", "park"],
    "age": [20, 25, 30]
})
df

   name  age
0   kim   20
1  hong   25
2  park   30

In [50]:
df['age'] = df['age'] + 10
df

   name  age
0   kim   30
1  hong   35
2  park   40

In [51]:
df['age'] = df['age'].apply(lambda a : a+10)
df

   name  age
0   kim   40
1  hong   45
2  park   50

In [53]:
df['etc'] = df['age'].apply(lambda a : '성인' if a>=45  else '미성년')
df

   name  age  etc
0   kim   40  미성년
1  hong   45   성인
2  park   50   성인