# **컨프리헨션 & 람다**

* <b>for문 1~10 짝수만 출력

In [1]:
for n in range(1,11) :
    if  (n%2 == 0) :
        print(n)

2
4
6
8
10

In [2]:
[n for n in range(1,11) if  (n%2 == 0) ]

[2, 4, 6, 8, 10]

* <b>for문 1~5 3보다 크면 값*2, 그렇지 않으면 값 출력

In [3]:
for n in range(1,6) :
    if  (n>3) :
        print(n*2)
    else:
        print(n)

1
2
3
8
10

In [4]:
[n*2 if(n>3) else n for n  in range(1,6)]

[1, 2, 3, 8, 10]

# **람다(Lamda)**
* 익명(이름없는) 함수
* 1회용

* <b>함수이름 : add 
* 파라미터 : 숫자2개
* 합산 결과 리턴

In [22]:
def add(a, b) : 
    res = a + b
    return res

In [23]:
a = add(1,2)
print(a)

3

In [24]:
def ncheck(n) : 
    print(n*2)

ncheck(6)

12

In [25]:
myf = lambda n : n*2

In [26]:
myf(6)

12

In [28]:
ncheck(6)

12

* <b>람다 예제

In [19]:
def add(a, b) : 
    res = a + b
    return res

a=add(1, 2)
print(a)

3

In [29]:
add2 = lambda a, b : a + b

a= add2(1 ,2)
print(a)

3

* <b>람다 예제

In [40]:
n if n > 10 else 0

if n > 10 :
    n
else:
    0

n if n > 10 else 0

0

In [38]:
a=lambda n : n if n > 10 else None
a(30)

30

* <b>람다 예제

In [41]:
def add(n1) : 
    res = n1 +10
    return res

a = lambda n1 : n1+10
a(5)

15

* <b>람다 예제

In [42]:
def check(n1) : 
    if n1 >10 : 
        res + n1 * 2
    else :
        res = n1
    return res

check(2)

2

In [47]:
import numpy as np
import pandas as pd

In [48]:
df = pd.DataFrame({
    "name": ["kim", "hong", "park"],
    "age": [20, 25, 30]
})
df

   name  age
0   kim   20
1  hong   25
2  park   30

In [49]:
df['age'] = df['age'] + 10
df

   name  age
0   kim   30
1  hong   35
2  park   40

In [50]:
df['age'] = df['age'].apply(lambda a :a+10)
df

   name  age
0   kim   40
1  hong   45
2  park   50