# **10 minutes to pandas**
* https://pandas.pydata.org/docs/user_guide/10min.html#
* pip install numpy, pandas

# **기본 구조**
* <font color=red><b>Series: 1차(one-dimensional) 데이터
* <font color=red><b>DataFrame: 2차(two-dimensional) 데이터 (like table)

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*OaUbgSxKnC_kaRj0H6vK5Q.jpeg" widcth=400>
<pre>  단일값[0]   리스트,튜플,딕[1]    Series[1]      DataFrame[2]             Tensor[3]

In [1]:
import numpy  as np
import pandas as pd

# **C : 생성**
* pd.Series()
* pd.DataFrame()

In [2]:
mylist = [1, 3, 5, np.nan, 6, 8]
print(mylist)

s = pd.Series(mylist)
print(s)

[1, 3, 5, nan, 6, 8]
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
mylist =  [  [1, 3, 5, np.nan, 6, 8] ,
             [1, 3, 5, np.nan, 6, 8] ,
             [1, 3, 5, np.nan, 6, 8]
          ]   
df2 = pd.DataFrame(mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
df2

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [4]:
df2.iloc[1: , 0:3]

    a  b  c
20  1  3  5
30  1  3  5

In [5]:
df2.loc[20: , "a":"c"]

    a  b  c
20  1  3  5
30  1  3  5

In [6]:
mydict = {"a":[1,1,1] , "b":[3,3,3]  , "c":[5,5,5]}
df = pd.DataFrame(mydict)
df

   a  b  c
0  1  3  5
1  1  3  5
2  1  3  5

# **Viewing data**
* <font color=red><b>df.info() </b></font>
* df.shape : 행*열
* df.index : 인덱스
* df.columns : 컬럼이름
* df.head() / df.tail()

* https://www.kaggle.com/datasets/arunjathari/bostonhousepricedata

<pre>
| **CRIM**    | 범죄율         | 지역별 1인당 범죄율                  |
| **ZN**      | 주거지역 비율     | 25,000 sq.ft 초과 주거용 토지 비율    |
| **INDUS**   | 비소매 상업지역 비율 | 비소매업 용도의 토지 비율               |
| **CHAS**    | 찰스강 인접 여부   | 찰스강에 접하면 **1**, 아니면 **0**    |
| **NOX**     | 일산화질소 농도    | 대기오염 정도를 나타내는 질소산화물 농도       |
| **RM**      | 평균 방 개수     | 주택 한 채당 평균 방(Room) 수         |
| **AGE**     | 오래된 주택 비율   | 1940년 이전에 지어진 주택 비율          |
| **DIS**     | 고용센터까지 거리   | 보스턴의 주요 고용센터 5곳까지의 가중 거리     |
| **RAD**     | 고속도로 접근성    | 방사형 고속도로 접근성 지수              |
| **TAX**     | 재산세율        | $10,000당 재산세율                |
| **PTRATIO** | 학생/교사 비율    | 지역별 학생 대 교사 비율               |
| **B**       | 인구 관련 변수    | 원본 데이터에서 흑인 인구 비율을 변환해 만든 변수 |
| **LSTAT**   | 저소득층 비율     | 낮은 사회경제적 지위 인구의 비율(%)        |
| **MEDV**    | 주택가격        | 주택가격 중앙값, 단위는 **$1,000**     |

In [7]:
df = pd.read_csv("../datas/Boston-house-price-data.csv")
df.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

In [8]:
df.shape

(506, 14)

In [9]:
df.index

RangeIndex(start=0, stop=506, step=1)

In [10]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [11]:
df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS         int64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [13]:
df.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

In [14]:
df.tail(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

# **Selection**
* []
* df.at() df.iat()
* df.loc() df.iloc()

* 연습을 위해 샘플링 후 일부 데이터만 사용

In [15]:
df = df[0:5].copy()

In [16]:
df.shape

(5, 14)

In [17]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## []

In [18]:
df["CRIM"]

0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
Name: CRIM, dtype: float64

In [19]:
df[["CRIM","B"]]

      CRIM       B
0  0.00632  396.90
1  0.02731  396.90
2  0.02729  392.83
3  0.03237  394.63
4  0.06905  396.90

## 슬라이싱

In [20]:
df[0:2]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

In [21]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## **loc / iloc**

In [22]:
df.iloc[0:2, 0:3]

      CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07

In [23]:
df.iloc[2:5, 2:5]

   INDUS  CHAS    NOX
2   7.07     0  0.469
3   2.18     0  0.458
4   2.18     0  0.458

In [24]:
df.loc[2:3, "INDUS":"NOX"]

   INDUS  CHAS    NOX
2   7.07     0  0.469
3   2.18     0  0.458

In [25]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [26]:
df.iloc[ [0,2,4]    ,  [0,1,2,-1] ]

      CRIM    ZN  INDUS  MEDV
0  0.00632  18.0   2.31  24.0
2  0.02729   0.0   7.07  34.7
4  0.06905   0.0   2.18  36.2

In [27]:
df.loc[ [0,2,4]    ,  ["CRIM","ZN","INDUS","MEDV"] ]

      CRIM    ZN  INDUS  MEDV
0  0.00632  18.0   2.31  24.0
2  0.02729   0.0   7.07  34.7
4  0.06905   0.0   2.18  36.2

In [28]:
#df
#df.iloc[0: , 0: ]
df.iloc[ : , : ]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## **at / iat**

In [29]:
df.iat[0, 1]

np.float64(18.0)

In [30]:
df.at[0, "ZN"]

np.float64(18.0)

## index 값  int vs. str 주의

* index 값 int

In [31]:
df3 = pd.DataFrame( {"a":[1,2,3], "b":[10,20,30]} , index=[10,20,30])
print(df3.index)
print(  df3.loc[ 10:20 ,  "a"  ] )
df3

Index([10, 20, 30], dtype='int64')
10    1
20    2
Name: a, dtype: int64

    a   b
10  1  10
20  2  20
30  3  30

* index 값 str

In [32]:
df3 = pd.DataFrame( {"a":[1,2,3], "b":[10,20,30]} , index=['10','20','30'])
print(df3.index)
print( df3.loc[ '10':'20' ,  "a"  ]  )
df3

Index(['10', '20', '30'], dtype='str')
10    1
20    2
Name: a, dtype: int64

    a   b
10  1  10
20  2  20
30  3  30

# **Missing data**
* 결측 : NaN , null, np.nan
* <font color=red><b>fillna() : 채우기(보간)
* <font color=red><b>dropna() : 버리기
* <font color=red><b>isna() : 결측체크

In [33]:
mylist =  [  [1, 3, 5, np.nan, 6, 8] ,
             [1, 3, 5, np.nan, 6, 8] ,
             [1, 3, 5, np.nan, 6, 8]
          ]   
df2 = pd.DataFrame(mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
df2

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

## 컬럼 가감산

In [34]:
df2['a'] + df2['b']

10    4
20    4
30    4
dtype: int64

In [35]:
df2['a'] + 10

10    11
20    11
30    11
Name: a, dtype: int64

In [36]:
df2['xx'] = df2['a'] + df2['b']
df2

    a  b  c   d  e  f  xx
10  1  3  5 NaN  6  8   4
20  1  3  5 NaN  6  8   4
30  1  3  5 NaN  6  8   4

* <font color=red><b>결측이 있는 'd' 컬럼은 어떠한 연산을 가해도 결측이다

In [37]:
df2['a'] + df2['d']

10   NaN
20   NaN
30   NaN
dtype: float64

## 결측 찾기

In [38]:
df2.isna()

        a      b      c     d      e      f     xx
10  False  False  False  True  False  False  False
20  False  False  False  True  False  False  False
30  False  False  False  True  False  False  False

In [39]:
df2.isna().sum()

a     0
b     0
c     0
d     3
e     0
f     0
xx    0
dtype: int64

In [40]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 10 to 30
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       0 non-null      float64
 4   e       3 non-null      int64
 5   f       3 non-null      int64
 6   xx      3 non-null      int64
dtypes: float64(1), int64(6)
memory usage: 192.0 bytes

## 결측 채우기(보간)

In [41]:
###df2 = df2.fillna(0)
df2.fillna(0, inplace=True)

    a  b  c    d  e  f  xx
10  1  3  5  0.0  6  8   4
20  1  3  5  0.0  6  8   4
30  1  3  5  0.0  6  8   4

In [42]:
df2

    a  b  c    d  e  f  xx
10  1  3  5  0.0  6  8   4
20  1  3  5  0.0  6  8   4
30  1  3  5  0.0  6  8   4

## 결측 삭제
* <font color=red>df.dropna(axis=0) : 행(줄,가로,↓)지우기
* <font color=red>df.dropna(axis=1) : 열(칸,세로,→)지우기
* <font color=red>df.dropna(subset=['컬럼']) : 컬럼에 결측 지우기
* <font color=red>df.drop(columns=['컬럼']) : 컬럼 삭제

In [43]:
mylist =  [  [1, 3, 5, np.nan, 6, 8] ,
             [1, 3, np.nan, 5,  np.nan, 8] ,
             [1, 3, np.nan, 6, 6, 8],
             [1, 3, 5, 6, 6, 8],
          ]   
df2 = pd.DataFrame(mylist, index=[10,20,30,40], columns=['a','b','c','d','e','f'])
df33 = df2.copy()
df44 = df2.copy()
df55 = df2.copy()

* <font color=red><b>df.dropna(axis=0) : 행(줄,가로,↓)지우기
* 그 줄에 결측이 있으면 줄을 지워라

In [44]:
df33 = df33.dropna(axis=0)
###df33.dropna(axis=0, inplace=True)

In [45]:
df33

    a  b    c    d    e  f
40  1  3  5.0  6.0  6.0  8

* <font color=red><b>df.dropna(axis=1) : 열(칸,세로,→)지우기

In [46]:
df44

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  6.0  8
40  1  3  5.0  6.0  6.0  8

In [47]:
df44 = df44.dropna(axis=1)
###df44.dropna(axis=1, inplace=True)

In [48]:
df44

    a  b  f
10  1  3  8
20  1  3  8
30  1  3  8
40  1  3  8

* <font color=red><b>df.dropna(subset=['컬럼']) : 컬럼에 결측 지우기

In [49]:
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  6.0  8
40  1  3  5.0  6.0  6.0  8

In [50]:
df55 = df55.dropna(subset=['c'])

In [51]:
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
40  1  3  5.0  6.0  6.0  8

* <font color=red><b>df.drop(columns=['컬럼']) : 컬럼 삭제

In [52]:
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
40  1  3  5.0  6.0  6.0  8

In [53]:
df55 = df55.drop(columns=['a','b'])

In [54]:
df55

      c    d    e  f
10  5.0  NaN  6.0  8
40  5.0  6.0  6.0  8

# **stat.**
* 통계(statistics)

In [55]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## describe()

In [56]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,5.000000,5.000000,5.000000,5.0,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.032468,3.600000,4.162000,0.0,0.478400,6.865200,61.040000,5.229720,2.20000,244.800000,17.660000,395.632000,5.284000,29.980000
std,0.022778,8.049845,2.655159,0.0,0.033768,0.346716,12.402943,0.840081,0.83666,30.318311,1.393915,1.849235,2.346813,6.682963
min,0.006320,0.000000,2.180000,0.0,0.458000,6.421000,45.800000,4.090000,1.00000,222.000000,15.300000,392.830000,2.940000,21.600000
25%,0.027290,0.000000,2.180000,0.0,0.458000,6.575000,54.200000,4.967100,2.00000,222.000000,17.800000,394.630000,4.030000,24.000000
50%,0.027310,0.000000,2.310000,0.0,0.469000,6.998000,61.100000,4.967100,2.00000,242.000000,17.800000,396.900000,4.980000,33.400000
75%,0.032370,0.000000,7.070000,0.0,0.469000,7.147000,65.200000,6.062200,3.00000,242.000000,18.700000,396.900000,5.330000,34.700000
max,0.069050,18.000000,7.070000,0.0,0.538000,7.185000,78.900000,6.062200,3.00000,296.000000,18.700000,396.900000,9.140000,36.200000

## value_counts()

In [57]:
df['RAD'].value_counts()

RAD
2    2
3    2
1    1
Name: count, dtype: int64

## .str.함수()

In [58]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [59]:
df.columns.str.lower()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='str')

# **★★★Grouping★★★**
* max() , min(), mean(), sum(), count(), std()

In [60]:
df77 = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df77.head(3)

     A  B    C         D         E
0  one  A  foo -2.147822 -0.145931
1  one  B  foo -1.704185  0.780099
2  two  C  foo  1.186660  0.808776

In [61]:
df77.groupby("A")["D"].min()

A
one     -2.147822
three   -1.539421
two     -0.048351
Name: D, dtype: float64

In [62]:
df77.groupby("A")["D"].agg(['min','max'])

            min       max
A
one   -2.147822  0.499335
three -1.539421  0.641087
two   -0.048351  1.186660

In [63]:
#df77.groupby("A")["D"].agg(  ['min','max']  )
df77.groupby("A")      .agg(  {"D":"min",   "E":"max"}  )

              D         E
A
one   -2.147822  0.920420
three -1.539421 -0.412810
two   -0.048351  0.932741

# **concat vs. merge**

## **pd.concat([adf, bdf],  axis=)**
* <font color=red><B>0 : 위(2) 아래(3)  = 총5줄
* <font color=red><B>1 : 열(2) 열(3)    = 총5열

In [64]:
dfa = pd.DataFrame({"a" : [1,2,3] , "b":[10,20,30]})
dfb = pd.DataFrame({"a" : [4,5]   , "b":[40,50]})

In [65]:
dfa

   a   b
0  1  10
1  2  20
2  3  30

In [66]:
dfb

   a   b
0  4  40
1  5  50

In [67]:
dfab = pd.concat( [dfa, dfb], axis=0)
dfab = dfab.reset_index(drop=True)  #-----------인덱스 정리
dfab

   a   b
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [68]:
dfab = pd.concat( [dfa, dfb], axis=1)
dfab.columns = ['a','b','c','d']  #-----------컬럼 정리
dfab

   a   b    c     d
0  1  10  4.0  40.0
1  2  20  5.0  50.0
2  3  30  NaN   NaN

## **pd.merge(adf, bdf  , on="컬럼", how="inner/outer")**
* <font color=red><B>0 : 위(2) 아래(3)  = 총5줄
* <font color=red><B>1 : 열(2) 열(3)    = 총5열

In [69]:
dfab = pd.merge(dfa,dfb, left_index=True, right_index=True, how='inner')
dfab

   a_x  b_x  a_y  b_y
0    1   10    4   40
1    2   20    5   50

In [70]:
dfab = pd.merge(dfa, dfb, left_index=True, right_index=True, how='outer')
dfab

   a_x  b_x  a_y   b_y
0    1   10  4.0  40.0
1    2   20  5.0  50.0
2    3   30  NaN   NaN

In [71]:
left = pd.DataFrame({"key": ["foo", "foo2"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo2"], "rval": [4, 5]})

In [72]:
left

    key  lval
0   foo     1
1  foo2     2

In [73]:
right

    key  rval
0   foo     4
1  foo2     5

In [74]:
dfab = pd.merge(left, right, on="key", how='inner')
dfab

    key  lval  rval
0   foo     1     4
1  foo2     2     5